const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(__dirname+'/public/index.html','utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
const stub={classList:{contains:()=>false,add(){},remove(){},toggle(){}},style:{},addEventListener(){},querySelectorAll:()=>[],innerHTML:''};
const ctx=vm.createContext({WalletLens:require('./public/wallet-lens'),console,Intl,Map,Set,Date,localStorage:{getItem:()=>'{broken'},document:{getElementById:()=>stub,querySelectorAll:()=>[],addEventListener(){}},requestAnimationFrame:()=>{},setTimeout:()=>{},setInterval:()=>{}});
vm.runInContext(script.replace(/loadUniverse\(false\);\s*$/,''),ctx);
const run=code=>vm.runInContext(code,ctx);
assert.equal(run('pct(0.194)'),'+19.4%');
assert.equal(run('pct(-0.0032)'),'-0.32%');
assert.equal(run('pct(null)'),'—');
assert.equal(run('formatPrice(0.0179342)'),'$0.0179342');
assert.equal(run('formatPrice(0.0000000001234567)'),'$0.0000000001234567');
assert.equal(run("state.sort='outflow';sortValue({netflow:null})"),-Infinity);
assert.equal(run('sortValue({netflow:-20})'),20);
assert.equal(run("state.sort='inflow';JSON.stringify([{netflow:null},{netflow:-1000},{netflow:0},{netflow:100}].sort((a,b)=>sortValue(b)-sortValue(a)).map(t=>t.netflow))"),'[100,0,-1000,null]');
assert.equal(run("state.sort='outflow';JSON.stringify([{netflow:null},{netflow:-1000},{netflow:0},{netflow:100}].sort((a,b)=>sortValue(b)-sortValue(a)).map(t=>t.netflow))"),'[-1000,0,100,null]');
assert.equal(run('watch.length'),0);
for (const [hours,expected] of [[.5,[true,false,false,false]],[1,[true,false,false,false]],[2,[true,false,false,false]],[5.99,[true,false,false,false]],[6,[true,true,false,false]],[24,[true,true,true,false]],[167.99,[true,true,true,false]],[168,[true,true,true,true]]]) {
 assert.equal(run(`JSON.stringify(DETAIL_TFS.map(tf=>timeframeAllowed({id:'age-test',token_age_hours:${hours}},tf)))`),JSON.stringify(expected));
}
assert.equal(run("tfLabel('1h',{id:'young',token_age_hours:.5})"),'Since launch');
assert.equal(run("timeframeAllowed({id:'unknown'},'7d')"),true);
assert.equal(run("timeframeButtons({id:'young',token_age_hours:2},'1h').match(/disabled aria-disabled/g).length"),3);
assert.match(run("timeframeNote({id:'unknown'})"),/unknown/);
assert.equal(run("timeframeAllowed({id:'date',token_deployment_date:new Date(Date.now()-2*3600000).toISOString(),token_age_hours:200},'6h')"),false);
assert.equal(run("riskCheck({},null,{},'7d').key"),'insufficient');
assert.equal(run("nansenTokenUrl({chain:'solana',token_address:'AbC123'})"),'https://app.nansen.ai/token-god-mode?chain=solana&tab=transactions&tokenAddress=AbC123');
run("DATA.views.foryou=[{id:'a',token_symbol:'A',chain:'base',token_address:'0xabc'}];detailToken=DATA.views.foryou[0];detailTf='7d';snapshotByKey.set('a|7d',{ok:true,data:{price_change:null,nof_buyers:null,nof_sellers:null}});renderDetail(detailToken)");
assert.match(stub.innerHTML,/Buyer\/seller counts unavailable/);
assert.doesNotMatch(stub.innerHTML,/Unique buyers/);
const {keyOf,getSnapshot,getInfo,getUniverse}=require('./server');
assert.notEqual(keyOf('solana','AbC'),keyOf('solana','abc'));
assert.equal(keyOf('base','0xAbC'),keyOf('base','0xabc'));
let requests=[];
global.fetch=async(url,opts)=>{
 const body=JSON.parse(opts.body);requests.push({url,body});
 let data=url.endsWith('token-information')?{data:{spot_metrics:{unique_buyers:5,unique_sellers:0,total_buys:8,total_sells:0}}}:{data:[{chain:body.chains[0],token_address:body.filters.token_address,token_symbol:'TEST',price_change:.194}]};
 return {ok:true,headers:{get:()=>null},text:async()=>JSON.stringify(data)};
};
(async()=>{
 const blocked=await run("fetchSnapshot({id:'young',token_age_hours:2},'7d')");
 assert.equal(blocked.ok,false);
 const snap=await getSnapshot('base','0xabc','24h');
 assert.equal(snap.data.nof_buyers,5);assert.equal(snap.data.nof_sellers,0);assert.equal(snap.data.price_change,.194);
 assert.equal(requests[1].body.timeframe,'1d');
 await getSnapshot('base','0xabc','24h');assert.equal(requests.length,2);
 await getInfo('base','0xabc','6h');assert.equal(requests[2].body.timeframe,'6h');
 global.fetch=async()=>({ok:true,headers:{get:()=>null},text:async()=>JSON.stringify({data:[{chain:'base',token_address:'wrong',token_symbol:'WRONG'}]})});
 assert.equal((await getSnapshot('base','0xmissing','7d')).ok,false);
 global.fetch=async(url,opts)=>({ok:!url.endsWith('token-information'),status:503,headers:{get:()=>null},text:async()=>JSON.stringify(url.endsWith('token-information')?{message:'Unavailable'}:{data:[{chain:'base',token_address:'0xfail',token_symbol:'OK',volume:10}]})});
 const partial=await getSnapshot('base','0xfail','1h');assert.equal(partial.ok,true);assert.equal(partial.data.volume,10);assert.equal(partial.data.nof_buyers,null);
 global.fetch=async()=>{throw new Error('Offline')};
 await assert.rejects(getUniverse(true),/All chains failed/);
 global.fetch=async(url,opts)=>{const b=JSON.parse(opts.body);return {ok:true,headers:{get:()=>null},text:async()=>JSON.stringify({data:[{chain:b.chains[0],token_address:'fixture',token_symbol:'FIX',volume:10}],pagination:{is_last_page:true}})}};
 const universe=await getUniverse(true);assert.equal(universe.counts.raw,7);
 global.fetch=async()=>{throw new Error('Offline')};
 const stale=await getUniverse(true);assert.equal(stale.stale,true);assert.equal(stale.generated_at,universe.generated_at);assert.equal(stale.counts.raw,7);
 let concurrent=0;
 global.fetch=async(url,opts)=>{concurrent++;await new Promise(r=>setTimeout(r,5));const b=JSON.parse(opts.body);return {ok:true,headers:{get:()=>null},text:async()=>JSON.stringify(url.endsWith('token-information')?{data:{spot_metrics:{unique_buyers:4}}}:{data:[{chain:'base',token_address:b.filters.token_address,token_symbol:'CON'}]})}};
 await Promise.all([getSnapshot('base','0xparallel','6h'),getSnapshot('base','0xparallel','6h')]);assert.equal(concurrent,2);
 assert.equal(run("fresh({ok:true,fetched_at:new Date(Date.now()-600000).toISOString()})"),false);
 assert.equal(run("fresh({ok:false,fetched_at:new Date(Date.now()-20000).toISOString()})"),false);
 assert.equal(run("savedToken({id:'solana:AbCd',chain:'solana',symbol:'OLD'}).token_address"),'AbCd');
 console.log('PASS: formatting, missing-data, sort, storage recovery, risk, links, address identity, timeframe mapping, participation, cache and partial failures');
})().catch(e=>{console.error(e);process.exitCode=1});
